url: "https://mariakatsourani.github.io/recipe-archive/"
baseurl: ""

# Build settings
markdown: kramdown

source: content

permalink: pretty

collections:
  recipes:
    output: true

defaults:
  - scope:
      type: recipes
    values:
      layout: post